- hosts: all
  become: yes
  
  tasks:

  - name: ensure aptitude is installed
    package:
      name: "aptitude"
      state: present
      
  - name: update apt-cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600

  - name: Upgrade all packages and kernel
    apt: 
      upgrade: dist

  - name: reboot to apply latest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: wait for 10 seconds
    pause:
      seconds: 10

  - name: wait for boot cycle to complete and reconnect
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60
