- hosts: all
  become: yes
  tasks:

  - name: ensure aptitude is installed
    become: yes
    become_user: root
    become_method: sudo
    package:
      name: aptitude
      state: present

  - name: update apt-cache
    become: yes
    become_user: root
    become_method: sudo    
    apt: 
      update_cache: yes 
      cache_valid_time: 3600

  - name: Upgrade all packages and kernel
    become: yes
    become_user: root
    become_method: sudo
    apt: 
      upgrade: dist

  - include: reboot.yml